services:
  kafka-consumer:
    image: dannymvp/kafka-consumer
    container_name: kafka-consumer
    ports:
      - "8090:8090"
    environment:
      BOOTSTRAP_SERVERS: broker:29092
      PYTHONUNBUFFERED: 1
      TOPIC_NAME: danny-topic
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true