consumer-impl:
  consumer:
    topic_name: danny-topic
    bootstrap_servers: broker:29092
    auto_offset_reset: latest
    value_deserializer: "lambda m: json.loads(m.decode('utf-8')) if m else None"